config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    devise_for :users, :controllers => {
      :sessions => 'users/sessions',
      :passwords => "users/passwords",
      :registrations => 'users/registrations'
    }
    devise_for :admins,
      :controllers => { :sessions => 'admins/sessions' }
  else
    devise_for :users,
      :controllers => { :sessions => 'users/sessions' },
      :only => [ :session ]
    devise_for :admins,
      :controllers => { :sessions => 'admins/sessions' },
      :only => [ :session ]
  end

  root 'users/accounts#top'

  resource :health_check, only: [:show]

  scope module: :users do
    namespace :oauth do
      resource :authorization, only: [:create] do
        get '/', action: :create
        post 'sign_in_with_email_password', action: :sign_in_with_email_password
      end
    end
    resource :account, only: [:show] do
      get '/top' => 'accounts#top', on: :collection, :as => :top
      resources :addresses, only: [:index, :edit, :update, :new, :create, :destroy] do
        collection do
          get 'fetch_address_with_zipcode', action: :fetch_address_with_zipcode, :as => :fetch_address
        end
      end
    end
    resource :profile, only: [:edit, :create, :update] do
      resources :credit_cards, only: [:index, :new, :edit, :create, :destroy]
    end
    resources :products, only: [:index, :show] do
      collection do
        get ':id/show_one_click/', action: :show_one_click, :as => :show_one_click
        get ':id/description', action: :description, :as => :description
        get 'update_max_used_point', action: :update_max_used_point, :as => :update_max_used_point
        post :post_one_click_order
      end
    end
    resource :cart, only: [:update], controller: :orders do
      get '/', action: :edit
      get :address, on: :member
      patch '/remove_item/:id' => 'orders#remove_item', on: :collection, :as => :remove_item
    end
    resources :orders, only: [:show] do
      collection do
        get 'single_history'
        get 'one_click_history'
        post :populate
        get  ':number/thanks', action: :thanks, :as => :thanks
        get  ':number/one_click_thanks', action: :one_click_thanks, :as => :one_click_thanks
        patch '/cancel/:number' => 'orders#cancel', :as => :cancel
        patch '/one_click_cancel/:number' => 'orders#one_click_cancel', :as => :one_click_cancel
      end
    end
    namespace :orders do
      resources :items, only: [] do
        get  'send_back_confirmation'
        post 'request_send_back'
      end
    end

    get '/checkout/:state', :to => 'checkouts#edit', :as => :checkout_state
    patch '/checkout/:state', :to => 'checkouts#update', :as => :update_checkout
    get '/t/*id', :to => 'taxons#show', :as => :taxons #nested_taxon
    get '/guidances/:name', :to => 'guidances#show', :as => :guidance
  end

  namespace :admins do
    resources :products do
      resources :variants, only: [:index, :new, :create, :edit, :update, :destroy]
      get '/move_position', :to => 'products#move_position', :as => :move_position
    end
    resources :variants, only: [] do
      resources :images,only: [:index, :new, :create, :edit, :update, :destroy], controller: :images, imageable_type: 'Variant'
      post '/images/sort', :to => 'images#sort'
    end
    namespace :shipments do
      resources :singles, only:[:index, :show, :update] do
        collection do
          get 'state/:state', :to => 'singles#index', :as => :state
          get 'return_requests'
          get 'shipment_details'
          get 'csv_export'
          patch 'update_tracking_code', :to => 'singles#update_tracking_code', :as => :update_tracking_code
          patch 'update_state', :to => 'singles#update_state', :as => :update_state
        end
      end
      resources :one_clicks, only:[:index, :show, :update] do
        collection do
          get 'state/:state', :to => 'one_clicks#index', :as => :state
          get 'return_requests'
          get 'shipment_details'
          get 'csv_export'
          patch 'update_tracking_code', :to => 'one_clicks#update_tracking_code', :as => :update_tracking_code
          patch 'update_state', :to => 'one_clicks#update_state', :as => :update_state
        end
      end
    end
    #TODO routing setting
    namespace :bills do
      resources :credits, only: [:index, :show]
      resources :post_payments, only: [:index, :show]
      resources :subscriptions
      resources :one_clicks
    end
    resources :users, only:[:index, :show, :update] do
      collection do
        post 'search'
      end
    end
    resources :reports, only:[:index]
  end

end

app/controllers/admins/bills/one_clicks_controller.rb
class Admins::Bills::OneClicksController < Admins::BaseController

  include Admins::AuthenticationHelper

  before_action :allow_admins_and_nutritionists

  def index
    @payments = OneClickPayment.where(payment_method_id: PaymentMethod::CreditCard).includes(user:[:profile]).includes(one_click_detail: [one_click_item: [:variant]]).order("id DESC")
  end

  def show
    @detail = OneClickDetail.find(OneClickPayment.find_by(id: params[:id]).one_click_detail_id)
    @user = @detail.one_click_payment.user
    @office_address = @user.get_business_account['company']
  end
end

app/controllers/admins/shipments/one_clicks_controller.rb
class Admins::Shipments::OneClicksController < Admins::BaseController

  before_filter :set_shipments, only: [:shipment_details]
  before_filter :setup_for_current_state, only: [:index]

  def index
    @title ||= "全発送リスト"
  end

  def shipment_details
    payment_from_shipments(@shipments)
  end

  def update_state
    @shipments = OneClickShipment.where(id: shipment_ids_from_params).includes(one_click_item: [:variant])
    filter_for_update(@shipments)
    method_name = :"update_#{params[:state]}"
    send(method_name, @shipments) if respond_to?(method_name, true)
  end

  def csv_export
    begin
      ActiveRecord::Base.transaction do
        @shipments = OneClickShipment.where(id: params[:shipment_ids].split(' '))
        shipments_update_state(@shipments)
        respond_to do |format|
          format.html do
            @shipments = OneClickShipment.all
          end
          format.csv do
            send_data render_to_string, filename: "lunch.csv", type: :csv
          end
        end
      end
    rescue => e
      params['error_message'] = e.message
    end
  end


  private

    def set_shipments
      @shipments = OneClickShipment.where(id: shipment_ids).includes(one_click_item: [variant: [product: [:taxons]]])
      filter_for_update(@shipments)
    end

    def payment_from_shipments(shipments)
      @payment = OneClickPayment.find_by(one_click_detail_id: shipments.first.one_click_item.one_click_detail_id)
    end

    def filter_for_update(shipments) #FIXME
      redirect_to :back unless ( shipments.present? && has_same_state? && belongs_to_same_taxon? )
    end

    def shipment_ids_from_params
      params[:shipment_ids].split.map(&:to_i)
    end

    def setup_for_current_state
      @shipments = params[:state] ? OneClickShipment.send(params[:state]).includes(one_click_item: [:variant, one_click_detail: [one_click_payment: [user: [:profile] ]]]) : \
        OneClickShipment.all.includes(one_click_item: [:variant ,one_click_detail: [one_click_payment: [user: [:profile] ]]]).order("id DESC")
      method_name = :"before_#{params[:state]}"
      send(method_name) if respond_to?(method_name, true)
    end

    def has_same_state?
      @shipments.all? {|shipment| shipment.state == @shipments.first.state}
    end

    def belongs_to_same_taxon?
      @shipments.all? {|shipment| @shipments.first.one_click_item.variant.product.taxons.ids.include?(shipment.one_click_item.variant.product.taxons.ids.first)}
    end

    def shipment_ids
      return nil if params[:shipment].nil?
      shipment_ids = params[:shipment].require(:ids)
    end

    def before_ready
      @title = "未発送リスト"
    end

    def before_shipped
      @shipments = @shipments.order("id DESC")
      @title = "発送済リスト"
    end

    def before_canceled
      @shipments = @shipments.order("id DESC")
      @title = "キャンセルリスト"
    end

    def before_exported
      @shipments = @shipments.order("id DESC")
      @title = "csv出力済リスト"
    end

    def unknown_state?
      Shipment.transitionable_states.include?(params[:state])
    end

    def update_shipped(shipments)
      # UserMailer.delay.send_items_shipped_notification(shipments, payment_from_shipments(shipments))
      shipments_update_state(shipments)
      redirect_to :back
    end

    def update_canceled(shipments)
      redirect_to :back and return unless shipments.all? { |shipment| shipment.one_click_item.cancel_item }
      redirect_to :back
    end

    def shipments_update_state(shipments)
      shipments.each do |shipment|
        shipment.send("#{params[:state]}!")
      end
    end

end

app/controllers/admins/shipments/singles_controller.rb
class Admins::Shipments::SinglesController < Admins::BaseController

  before_filter :set_shipments, only: [:shipment_details]
  before_filter :setup_for_current_state, only: [:index]

  def index
    @title ||= "全発送リスト"
  end

  def shipment_details
  end

  def update_state
    @shipments = Shipment.where(id: shipment_ids_from_params).includes(single_line_item: [:variant])
    filter_for_update
    method_name = :"update_#{params[:state]}"
    send(method_name, @shipments) if respond_to?(method_name, true)
  end

  def return_requests
    @return_requested_items = ReturnedItem.includes(user: [:profile]).includes(single_line_item: [:shipment, variant: [:product], single_order_detail: [:payment]]).where(returned_at: nil)
    @title = "返品要望リスト"
  end

  def csv_export
    @shipments = Shipment.where(id: shipment_ids_from_params)
    respond_to do |format|
      format.html do
        @shipments = Shipment.all
      end
      format.csv do
        send_data render_to_string, filename: "FiNC#{Time.now.strftime('%y%m%d%H%M%S')}.csv", type: :csv
      end
    end
    update_exported
  end

  private

    def shipment_ids_from_params
      return nil if params[:shipment].nil?
      shipment_ids = params[:shipment].require(:ids)
    end

    def set_shipments
      @shipments = Shipment.where(id: shipment_ids_from_params).includes(:address, single_line_item: [:variant, single_order_detail: [payment: [:user]]] )
      filter_for_update
    end

    def filter_for_update
      redirect_to :back and return unless (has_same_state? && @shipments.present?)# && ordered_by_same_user?)
    end

    def has_same_state?
      @shipments.all? {|shipment| shipment.state == @shipments.first.state}
    end

    def set_tracking(shipments)
      if has_same_tracking?(shipments)
        @tracking = shipments.first.tracking
      end
      @button_value = @tracking.present? ? "変更" : "登録"
    end

    def setup_for_current_state
      @shipments = params[:state] ? Shipment.send(params[:state]).includes(single_line_item: [:variant, single_order_detail: [payment: [user: [:profile] ]]]) : \
        Shipment.all.includes(single_line_item: [:variant, single_order_detail: [payment: [user: [:profile] ]]]).order("id DESC")
      method_name = :"before_#{params[:state]}"
      send(method_name) if respond_to?(method_name, true)
    end

    def has_same_tracking?(shipments)
      shipments.first.tracking.present? && (shipments.all? {|shipment| shipment.tracking == shipments.first.tracking})
    end


    def before_ready
      @title = "未発送リスト"
    end

    def before_shipped
      @shipments = @shipments.order("id DESC")
      @title = "配送済リスト"
    end

    def before_canceled
      @shipments = @shipments.order("id DESC")
      @title = "キャンセルリスト"
    end

    def unknown_state?
      Shipment.transitionable_states.include?(params[:state])
    end

    def update_shipped(shipments)
      # UserMailer.delay.send_items_shipped_notification(shipments)
      shipments_update_state(shipments)
      redirect_to :back
    end

    def update_canceled(shipments)
      # 現在キャンセルは商品一つずつのみ対応
      shipments.first.single_line_item.cancel_item(payment_from_shipments(shipments))
      redirect_to admins_shipments_singles_path
    end

    def update_returned(shipments)
      ReturnedItem.find(params[:returned_item_id]).update(returned_at: Time.now)
      redirect_to :back
    end

    def update_exported
      begin
        ActiveRecord::Base.transaction do
          @shipments.each do |shipment|
            shipment.exported!
          end
        end
      rescue
        # redirect
      end
    end

    def shipments_update_state(shipments)
      shipments.each do |shipment|
        shipment.send("#{params[:state]}!")
      end
    end

end

app/controllers/admins/shipments_controller.rb
class Admins::ShipmentsController < Admins::BaseController
  before_filter :set_shipments, only: [:shipment_details]
  before_filter :setup_for_current_state, only: [:index]

  def index
    @title ||= "全発送リスト"
  end

  def shipment_details
    payment_from_shipments(@shipments)
    set_tracking(@shipments)
  end

  def update_state
    @shipments = Shipment.where(id: shipment_ids_from_params).includes(single_line_item: [:variant])
    filter_for_update(@shipments)
    method_name = :"update_#{params[:state]}"
    send(method_name, @shipments) if respond_to?(method_name, true)
  end

  def update_tracking_code
    shipment_ids_from_params.each do |shipment_id|
      Shipment.find(shipment_id).update(tracking: params[:tracking])
    end
    redirect_to :back
  end

  def return_requests
    @return_requested_items = ReturnedItem.includes(user: [:profile]).includes(single_line_item: [:shipment, variant: [:product], single_order_detail: [:payment]]).where(returned_at: nil)
    @title = "返品要望リスト"
  end

  private
    def set_shipments
      @shipments = Shipment.where(id: shipment_ids).includes(single_line_item: [:variant], )
      filter_for_update(@shipments)
    end

    def payment_from_shipments(shipments)
      @payment = Payment.find_by(single_order_detail_id: shipments.first.single_line_item.single_order_detail_id)
    end

    def filter_for_update(shipments)
      redirect_to :back and return unless (belongs_to_same_order_detail?(shipments) && has_same_state?(shipments) && shipments.present?)
    end

    def shipment_ids_from_params
      params[:shipment_ids].split.map(&:to_i)
    end

    def set_tracking(shipments)
      if has_same_tracking?(shipments)
        @tracking = shipments.first.tracking
      end
      @button_value = @tracking.present? ? "変更" : "登録"
    end

    def setup_for_current_state
      @shipments = params[:state] ? Shipment.send(params[:state]).includes(single_line_item: [:variant, single_order_detail: [payment: [user: [:profile] ]]]) : \
        Shipment.all.includes(single_line_item: [:variant, single_order_detail: [payment: [user: [:profile] ]]]).order("id DESC")
      method_name = :"before_#{params[:state]}"
      send(method_name) if respond_to?(method_name, true)
    end

    def belongs_to_same_order_detail?(shipments)
      shipments.all? {|shipment| shipment.single_line_item.single_order_detail_id == shipments.first.single_line_item.single_order_detail_id}
    end

    def has_same_state?(shipments)
      shipments.all? {|shipment| shipment.state == shipments.first.state}
    end

    def has_same_tracking?(shipments)
      shipments.first.tracking.present? && (shipments.all? {|shipment| shipment.tracking == shipments.first.tracking})
    end

    def shipment_ids
      return nil if params[:shipment].nil?
      shipment_ids = params[:shipment].require(:ids)
    end

    def before_ready
      @title = "未発送リスト"
    end

    def before_shipped
      @shipments = @shipments.order("id DESC")
      @title = "配送済リスト"
    end

    def before_canceled
      @shipments = @shipments.order("id DESC")
      @title = "キャンセルリスト"
    end

    def unknown_state?
      Shipment.transitionable_states.include?(params[:state])
    end

    def update_shipped(shipments)
      redirect_to :back and return unless has_same_tracking?(shipments)
      UserMailer.delay.send_items_shipped_notification(shipments, payment_from_shipments(shipments))
      shipments_update_state(shipments)
      redirect_to :back
    end

    def update_canceled(shipments)
      # 現在キャンセルは商品一つずつのみ対応s
      shipments.first.single_line_item.cancel_item(payment_from_shipments(shipments))
      redirect_to admins_shipments_path
    end

    def update_returned(shipments)
      ReturnedItem.find(params[:returned_item_id]).update(returned_at: Time.now)
      redirect_to :back
    end

    def shipments_update_state(shipments)
      shipments.each do |shipment|
        shipment.send("#{params[:state]}!")
      end
    end

end

app/helpers/admins/shipments_helper.rb
module Admins::ShipmentsHelper
end

app/views/admins/shipments/one_clicks/_nav.html.erb
<section class="content col-md-2 float-right">
<ul class="nav nav-pills nav-stacked">
  <li <%= 'class=active' if request.path_info == admins_shipments_one_clicks_path %>>
    <a href="<%= admins_shipments_one_clicks_path %>">全発送リスト一覧</a>
  </li>
  <li <%= 'class=active' if request.path_info == state_admins_shipments_one_clicks_path(state: "ready") %>>
    <a href="<%= state_admins_shipments_one_clicks_path(state: "ready") %>"><%="未発送一覧(#{OneClickShipment.ready.count})"%></a>
  </li>
  <li <%= 'class=active' if request.path_info == state_admins_shipments_one_clicks_path(state: "exported") %>>
    <a href="<%= state_admins_shipments_one_clicks_path(state: "exported") %>"><%="CSV出力済一覧(#{OneClickShipment.exported.count})"%></a>
  </li>
  <li <%= 'class=active' if request.path_info == state_admins_shipments_one_clicks_path(state: "shipped") %>>
    <a href="<%= state_admins_shipments_one_clicks_path(state: "shipped") %>">発送済み一覧</a>
  </li>
  <li <%= 'class=active' if request.path_info == state_admins_shipments_one_clicks_path(state: "canceled") %>>
    <a href="<%= state_admins_shipments_one_clicks_path(state: "canceled") %>">キャンセル一覧</a>
  </li>
</ul>
</section>

app/views/admins/shipments/one_clicks/_table.html.erb
<%= form_tag shipment_details_admins_shipments_one_clicks_path, method: "get" do %>
  <table class="table c-table">
    <thead>
      <tr>
        <th>支払い日</th>
        <th>注文番号</th>
        <th>発送状況</th>
        <th>商品SKU名</th>
        <th>名前</th>
        <th>税込金額</th>
        <th><%= submit_tag "詳細情報", class: '' %></th>
      </tr>
    </thead>
    <tbody>
      <% shipments and shipments.each do |shipment| %>
        <% payment = shipment.one_click_item.one_click_detail.one_click_payment %>
        <tr>
          <td><%= payment.created_at.strftime("%Y/%m/%d %H:%M") %></td>
          <td><%= payment.number %></td>
          <td><%= t("shipment.state.#{shipment.state}") %></td>
          <td><%= shipment.one_click_item.variant.name %></td>
          <td><%= payment.user.profile.try(:name) %></td>
          <td><%= number_to_currency(shipment.one_click_item.price.to_i * shipment.one_click_item.quantity.to_i) %></td>
          <td>
            <%= check_box_tag 'shipment[ids][]', shipment.id, false, {:class => 'shipment_check_box', :id => "shipment_#{shipment.id}"} %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/admins/shipments/one_clicks/index.html.erb
<div class="content-header">
  <h3>
    弁当発送管理（※注文・商品毎管理）
  </h3>
</div>
<section class="content col-md-10">
  <h4 class="box-title"><%= @title %></h4>
  <%= render partial: 'table', locals: {shipments: @shipments} %>
</section>
<section>
  <%= render partial: 'nav', locals: {} %>
</section>

app/views/admins/shipments/one_clicks/shipment_details.html.erb
<% detail = @payment.one_click_detail %>
<div class="content-header">
  <h3>
    <%= link_to '弁当発送管理', admins_shipments_one_clicks_path %> / <%= @payment.number %>
    <div class="u-float_right">
      <% if @shipments.all_state?(@shipments, 'shipped') %>
        <div class="btn btn-warning">発送済み</div>
      <% elsif @shipments.all_state?(@shipments, 'canceled') %>
        <div class="btn btn-danger">キャンセルされました</div>
      <% elsif @shipments.all_state?(@shipments, 'returned') %>
        <div class="btn btn-default">返品されました</div>
      <% elsif @shipments.all_state?(@shipments, 'failed') %>
        <div class="btn btn-default">取引が失敗しています</div>
      <% elsif @shipments.all_state?(@shipments, 'ready') %>
        <%= form_tag csv_export_admins_shipments_one_clicks_path(format: :csv), method: "get", class: "u-float_left" do %>
          <%= hidden_field_tag :state, "exported" %>
          <%= hidden_field_tag :shipment_ids, @shipments.ids %>
          <%= submit_tag "CSV出力", class: "btn btn-primary", data: { confirm: "本当に実行しますか？" } %>
        <% end %>
      <% elsif @shipments.all_state?(@shipments, 'exported') %>
        <%= form_tag update_state_admins_shipments_one_clicks_path, method: "patch", class: "u-float_left" do %>
          <%= hidden_field_tag :state, "shipped" %>
          <%= hidden_field_tag :shipment_ids, @shipments.ids %>
          <%= submit_tag "発送する", class: "btn btn-primary", data: { confirm: "本当に実行しますか？" } %>
        <% end %>
      <% end %>
    </div>
  </h3>
</div>

<section class="content">

  <div class="content col-md-9">
    <h4 class="box-title">購入商品<span style="color:red"><%= flash[:alert] %></span></h4>
    <table class="table c-table">
      <thead>
        <tr>
          <th>名前</th>
          <th>画像</th>
          <th>単価</th>
          <th>個数</th>
          <th>注文支払い合計</th>
          <th>購入者</th>
          <th>購入者メールアドレス</th>
          <th></th>
        </tr>
        <% @shipments.each do |shipment| %>
          <% item = shipment.one_click_item %>
          <% user = item.one_click_detail.one_click_payment.user %>
          <tr>
            <td><%= item.variant.sku %></td>
            <td><%= image_tag item.variant.images.first.try(:image).try(:url), class: "thumb" %></td>
            <td><%= number_to_currency(item.price) %></td>
            <td><%= item.quantity %></td>
            <td><%= number_to_currency(item.one_click_detail.paid_total) %></td>
            <td><%= user.profile.name %></td>
            <td><%= user.email %></td>
            <td>
              <% if shipment.ready? %>
                <%= form_tag update_state_admins_shipments_one_clicks_path(shipment), method: "patch", class: "u-float_left u-margin__left20" do %>
                  <%= hidden_field_tag :state, "canceled" %>
                  <%= hidden_field_tag :shipment_ids, @shipments.ids %>
                  <%= submit_tag "発送キャンセル", class: "btn btn-warning", data: { confirm: "本当に発送をキャンセルしますか？" } %>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </thead>
    </table>
  </div>

</section>