config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    devise_for :users, :controllers => {
      :sessions => 'users/sessions',
      :passwords => "users/passwords",
      :registrations => 'users/registrations'
    }
    devise_for :admins,
      :controllers => { :sessions => 'admins/sessions' }
  else
    devise_for :users,
      :controllers => { :sessions => 'users/sessions' },
      :only => [ :session ]
    devise_for :admins,
      :controllers => { :sessions => 'admins/sessions' },
      :only => [ :session ]
  end

  root 'users/accounts#top'

  resource :health_check, only: [:show]

  scope module: :users do
    namespace :oauth do
      resource :authorization, only: [:create] do
        get '/', action: :create
        post 'sign_in_with_email_password', action: :sign_in_with_email_password
      end
    end
    resource :account, only: [:show] do
      get '/top' => 'accounts#top', on: :collection, :as => :top
      resources :addresses, only: [:index, :edit, :update, :new, :create, :destroy] do
        collection do
          get 'fetch_address_with_zipcode', action: :fetch_address_with_zipcode, :as => :fetch_address
        end
      end
    end
    resource :profile, only: [:edit, :create, :update] do
      resources :credit_cards, only: [:index, :new, :edit, :create, :destroy]
    end
    resources :products, only: [:index, :show] do
      collection do
        get ':id/show_one_click/', action: :show_one_click, :as => :show_one_click
        get ':id/description', action: :description, :as => :description
        get 'update_max_used_point', action: :update_max_used_point, :as => :update_max_used_point
        post :post_one_click_order
      end
    end
    resource :cart, only: [:update], controller: :orders do
      get '/', action: :edit
      get :address, on: :member
      patch '/remove_item/:id' => 'orders#remove_item', on: :collection, :as => :remove_item
    end
    resources :orders, only: [:show] do
      collection do
        get 'single_history'
        get 'one_click_history'
        post :populate
        get  ':number/thanks', action: :thanks, :as => :thanks
        get  ':number/one_click_thanks', action: :one_click_thanks, :as => :one_click_thanks
        patch '/cancel/:number' => 'orders#cancel', :as => :cancel
        patch '/one_click_cancel/:number' => 'orders#one_click_cancel', :as => :one_click_cancel
      end
    end
    namespace :orders do
      resources :items, only: [] do
        get  'send_back_confirmation'
        post 'request_send_back'
      end
    end

    get '/checkout/:state', :to => 'checkouts#edit', :as => :checkout_state
    patch '/checkout/:state', :to => 'checkouts#update', :as => :update_checkout
    get '/t/*id', :to => 'taxons#show', :as => :taxons #nested_taxon
    get '/guidances/:name', :to => 'guidances#show', :as => :guidance
  end

  namespace :admins do
    resources :products do
      resources :variants, only: [:index, :new, :create, :edit, :update, :destroy]
      get '/move_position', :to => 'products#move_position', :as => :move_position
    end
    resources :variants, only: [] do
      resources :images,only: [:index, :new, :create, :edit, :update, :destroy], controller: :images, imageable_type: 'Variant'
      post '/images/sort', :to => 'images#sort'
    end
    namespace :shipments do
      resources :singles, only:[:index, :show, :update] do
        collection do
          get 'state/:state', :to => 'singles#index', :as => :state
          get 'return_requests'
          get 'shipment_details'
          get 'csv_export'
          patch 'update_tracking_code', :to => 'singles#update_tracking_code', :as => :update_tracking_code
          patch 'update_state', :to => 'singles#update_state', :as => :update_state
        end
      end
      resources :one_clicks, only:[:index, :show, :update] do
        collection do
          get 'state/:state', :to => 'one_clicks#index', :as => :state
          get 'return_requests'
          get 'shipment_details'
          get 'csv_export'
          patch 'update_tracking_code', :to => 'one_clicks#update_tracking_code', :as => :update_tracking_code
          patch 'update_state', :to => 'one_clicks#update_state', :as => :update_state
        end
      end
    end
    #TODO routing setting
    namespace :bills do
      resources :credits, only: [:index, :show]
      resources :post_payments, only: [:index, :show]
      resources :subscriptions
      resources :one_clicks
    end
    resources :users, only:[:index, :show, :update] do
      collection do
        post 'search'
      end
    end
    resources :reports, only:[:index]
  end

end

app/models/variant.rb
# == Schema Information
#
# Table name: variants
#
#  id            :integer          not null, primary key
#  sku           :string(255)      default("all"), not null
#  product_id    :integer
#  name          :string(255)
#  order_type    :integer
#  is_valid_at   :datetime
#  is_invalid_at :datetime
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Variant < ActiveRecord::Base
  belongs_to :product
  has_one :price
  has_many :images, :as => :imageable
  has_many :single_line_items
  has_many :variant_image_whereabouts
  has_one :one_click_item
  has_one :upper_used_point_limit

  accepts_nested_attributes_for :upper_used_point_limit
  accepts_nested_attributes_for :price

  include TimeValidityChecker

  enum order_type: {single_order: 1, subscription_order: 2}
  validates :product_id,
    uniqueness: {
      scope: [:order_type]
    }
  validates :sku, :name, :order_type, :product_id, :is_valid_at, :is_invalid_at, presence: true

  def has_image_and_price?
    ( price.present? && images.present? && variant_image_whereabouts.top.present? && variant_image_whereabouts.description.present? )
  end

  def available?
    return true if ( has_image_and_price? && (self.stock_quantity > 0) && active? )
    false
  end

  def self.available
    return Variant.none if VariantImageWhereabout.where(variant_id: Variant.available_ids).blank?

    available_variant_id_with_all_variant_images = \
      Variant.available_ids.select { |id| ( VariantImageWhereabout.where(variant_id: id).top.present? && VariantImageWhereabout.where(variant_id: id).description.present? ) }
    Variant.where(id: available_variant_id_with_all_variant_images).active(Time.now)
  end

  def self.available_ids
    variant_id_having_images_and_prices = Image.where(imageable_type: 'Variant').pluck(:imageable_id) & Price.pluck(:variant_id)
    # 現時点では在庫がなくても”売り切れ”として一覧には表示する
    # variant_id_with_stock = Variant.where('stock_quantity > ?', 0 ).active.pluck(:id)

    variant_id_having_images_and_prices# & variant_id_with_stock
  end

  def self.single_variant
    find_by(order_type: Variant.order_types['single_order'])
  end

  def self.subscription_variant
    find_by(order_type: Variant.order_types['subscription_order'])
  end

  def valid_point?(point, user, quantity)
    (point >= 0) && (point <= max_used_point(user, quantity))
  end

  def max_used_point(user, quantity)
    [user.max_used_point, (upper_used_point * quantity.to_i)].min
  end

  def upper_used_point
    UpperUsedPointLimit.find_by(variant_id: id).limit.to_i
  end

  def top_image
    images.where(id: VariantImageWhereabout.top.where(variant_id: id).pluck(:image_id)).order("position ASC").first.try(:image).try(:url)
  end

  def update_stock_quantity(changed_quantity)
    self.stock_quantity += changed_quantity
    save!
  end

  def belongs_to_one_click_shippment_taxons?
    Taxon::OneClickShippmentIds.include?(product.taxons.ids.first)
  end

end

app/controllers/admins/variants_controller.rb
class Admins::VariantsController < Admins::BaseController

  include Admins::AuthenticationHelper

  before_action :allow_only_admins

  before_action :set_variant, only: [:edit, :update, :destroy]
  before_action :set_price, only: [:update]
  before_action :set_product,only: [:index,:new,:edit]

  def index
    @variants = Variant.includes(:price) \
      .where(product_id: params[:product_id] )
  end

  def new
    @variant = Variant.new(product_id: params[:product_id])
  end

  def create
    begin
      ActiveRecord::Base.transaction do
        @variant = Variant.new(variant_attributes)
        @variant.save!
      end
      redirect_to admins_product_variants_path(product_id: params[:product_id])
    rescue
      @product = Product.find(@variant.product_id)
      render :new
    end
  end

  def edit
  end

  def update
    begin
      ActiveRecord::Base.transaction do
        @variant.update!(variant_attributes)
      end
      redirect_to admins_product_variants_path(product_id: params[:product_id])
    rescue
      @product = Product.find(@variant.product_id)
      render :edit
    end
  end

  def destroy
    @variant.update(is_invalid_at: Time.now-1)
    redirect_to admins_product_variants_path
  end

  private

    def variant_attributes
      params.require(:variant).permit(:is_valid_at, :is_invalid_at, :order_type, :sku, :name, :stock_quantity, upper_used_point_limit_attributes: :limit, price_attributes: :amount).merge(product_id: params[:product_id])
    end

    def set_variant
      @variant = Variant.find(params[:id])
    end

    def set_price
      @price = Price.find_or_initialize_by( variant_id: params[:id] )
    end

    def price_params
      params.require(:variant).require(:price).permit(:amount).merge(variant_id: @variant.id)
    end

    def set_product
      @product = Product.find(params[:product_id])
    end

end

app/views/admins/variants/_form.html.erb
<%= form_for([:admins, variant.product, variant]) do |v| %>
  <section class="content">
  <div class="box-body col-md-6">
    <%= v.hidden_field :sku, :value => "all" %>
      <div class="form-group">
        <p><%= v.label :name %></p>
        <%= v.text_field :name, placeholder: variant.product.name, class: "form-control" %>
      </div>
      <div class="form-group">
        <p><%= v.label :is_valid_at %></p>
        <%if params[:action]=="new" %>
          <%= v.datetime_local_field :is_valid_at, value: Date.today%><br/>
        <% else %>
          <%= v.datetime_local_field :is_valid_at %><br/>
        <% end %>
      </div>
      <div class="form-group">
        <p><%= v.label :is_invalid_at %></p>
        <%if params[:action]=="new" %>
          <p><%= v.datetime_local_field :is_invalid_at, value: Date.today+6*30 %></p>
        <% else %>
          <p><%= v.datetime_local_field :is_invalid_at %></p>
        <% end %>
      </div>
      <%= v.fields_for :price, @variant.price || Price.new do |p| %>
        <div class="form-group">
          <p><%= p.label :amount %></p>
          <p><%= p.text_field :amount, class: "form-control", value: variant.price.try(:amount) %></p>
        </div>
      <% end %>
      <%= v.fields_for :upper_used_point_limit, @variant.upper_used_point_limit || UpperUsedPointLimit.new do |u| %>
        <div class="form-group">
          <p><%= u.label :limit %></p>
          <p><%= u.text_field :limit, class: "form-control", value: variant.upper_used_point_limit.try(:limit) %></p>
        </div>
      <% end %>
      <div class="form-group">
        <p><%= v.label :stock_quantity %></p>
        <%= v.text_field :stock_quantity, class: "form-control" %>
      </div>
      <div class="form-group">
        <p>
          <%= v.select :order_type,{t('order_type.single_order') => "single_order", t('order_type.subscription_order') => "subscription_order"},{},{:class=>"form-control"} %>
        </p>
      </div>
      <div class="actions">
        <%= v.submit "登録", class: "btn" %>
      </div>
    </div>
    </section>
<% end %>

app/views/admins/variants/edit.html.erb
<div class="content-header">
  <h3>
    <%= link_to "商品一覧", admins_products_path %> / <%= @product.name %>
    <div class="u-float_right">
      <a href="<%= new_admins_product_variant_path %>" class="btn btn-primary">SKU追加</a>
    </div>
  </h3>
</div>
<%= render partial: 'form', locals: { variant: @variant } %>

app/views/admins/variants/index.html.erb
<div class="content-header">
  <h3>
    <%= link_to "商品一覧", admins_products_path %> / <%= @product.name %>
    <div class="u-float_right">
      <a href="<%= new_admins_product_variant_path %>" class="btn btn-primary">SKU追加</a>
    </div>
  </h3>
</div>
<section class="content col-md-10">
  <h4 class="box-title">SKU一覧</h4>
  <% if !@variants.blank? %>
    <table class="table c-table">
      <thead>
        <tr>
          <th>名前</th>
          <th>画像</th>
          <th>注文タイプ</th>
          <th>値段</th>
          <th>使用可能マイル上限</th>
          <th>状態</th>
          <th>在庫数</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      <% @variants.each do |v| %>
        <tr>
          <td><%= v.name %></td>
          <td><%= image_tag v.top_image, class: "thumb" %>(<%= v.images.count %>)</td>
          <td>
            <% if !v.order_type.nil? %>
              <%= t('order_type.'+v.order_type) %>
            <% end %></td>
          <td>
            <%= v.price.try(:amount) %>
          </td>
          <td>
            <%= v.upper_used_point_limit.try(:limit) %>
          </td>
          <td><%= t(v.classify_validity) %></td>
          <td><%= v.stock_quantity %></td>
          <td>
            <a href="<%= admins_variant_images_path(v.id) %>" class="btn btn-info btn-sm">
              <i class="fa fa-file-o"></i>画像
            </a>
            <a href="<%= edit_admins_product_variant_path(@product.id, v.id) %>" class="btn btn-warning btn-sm">
              <i class="fa fa-edit"></i>編集
            </a>
            <a href="<%= admins_product_variant_path(@product.id, v.id) %>" class="btn btn-success btn-sm" data-method="delete" data-confirm="本当に削除しますか？">
              <i class="fa fa-trash-o"></i>削除
            </a>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% else %>
    <span><%= flash[:notice] %></span>
    <p>現在SKUは登録されていません</p>
  <% end %>
</section>

app/views/admins/variants/new.html.erb
<div class="content-header">
  <h3>
    <%= link_to "商品一覧", admins_products_path %> / <%= @product.name %>
    <div class="u-float_right">
      <a href="<%= new_admins_product_variant_path %>" class="btn btn-primary">SKU追加</a>
    </div>
  </h3>
</div>
<%= render partial: 'form', locals: { variant: @variant } %>