config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    devise_for :users, :controllers => {
      :sessions => 'users/sessions',
      :passwords => "users/passwords",
      :registrations => 'users/registrations'
    }
    devise_for :admins,
      :controllers => { :sessions => 'admins/sessions' }
  else
    devise_for :users,
      :controllers => { :sessions => 'users/sessions' },
      :only => [ :session ]
    devise_for :admins,
      :controllers => { :sessions => 'admins/sessions' },
      :only => [ :session ]
  end

  root 'users/accounts#top'

  resource :health_check, only: [:show]

  scope module: :users do
    namespace :oauth do
      resource :authorization, only: [:create] do
        get '/', action: :create
        post 'sign_in_with_email_password', action: :sign_in_with_email_password
      end
    end
    resource :account, only: [:show] do
      get '/top' => 'accounts#top', on: :collection, :as => :top
      resources :addresses, only: [:index, :edit, :update, :new, :create, :destroy] do
        collection do
          get 'fetch_address_with_zipcode', action: :fetch_address_with_zipcode, :as => :fetch_address
        end
      end
    end
    resource :profile, only: [:edit, :create, :update] do
      resources :credit_cards, only: [:index, :new, :edit, :create, :destroy]
    end
    resources :products, only: [:index, :show] do
      collection do
        get ':id/show_one_click/', action: :show_one_click, :as => :show_one_click
        get ':id/description', action: :description, :as => :description
        get 'update_max_used_point', action: :update_max_used_point, :as => :update_max_used_point
        post :post_one_click_order
      end
    end
    resource :cart, only: [:update], controller: :orders do
      get '/', action: :edit
      get :address, on: :member
      patch '/remove_item/:id' => 'orders#remove_item', on: :collection, :as => :remove_item
    end
    resources :orders, only: [:show] do
      collection do
        get 'single_history'
        get 'one_click_history'
        post :populate
        get  ':number/thanks', action: :thanks, :as => :thanks
        get  ':number/one_click_thanks', action: :one_click_thanks, :as => :one_click_thanks
        patch '/cancel/:number' => 'orders#cancel', :as => :cancel
        patch '/one_click_cancel/:number' => 'orders#one_click_cancel', :as => :one_click_cancel
      end
    end
    namespace :orders do
      resources :items, only: [] do
        get  'send_back_confirmation'
        post 'request_send_back'
      end
    end

    get '/checkout/:state', :to => 'checkouts#edit', :as => :checkout_state
    patch '/checkout/:state', :to => 'checkouts#update', :as => :update_checkout
    get '/t/*id', :to => 'taxons#show', :as => :taxons #nested_taxon
    get '/guidances/:name', :to => 'guidances#show', :as => :guidance
  end

  namespace :admins do
    resources :products do
      resources :variants, only: [:index, :new, :create, :edit, :update, :destroy]
      get '/move_position', :to => 'products#move_position', :as => :move_position
    end
    resources :variants, only: [] do
      resources :images,only: [:index, :new, :create, :edit, :update, :destroy], controller: :images, imageable_type: 'Variant'
      post '/images/sort', :to => 'images#sort'
    end
    namespace :shipments do
      resources :singles, only:[:index, :show, :update] do
        collection do
          get 'state/:state', :to => 'singles#index', :as => :state
          get 'return_requests'
          get 'shipment_details'
          get 'csv_export'
          patch 'update_tracking_code', :to => 'singles#update_tracking_code', :as => :update_tracking_code
          patch 'update_state', :to => 'singles#update_state', :as => :update_state
        end
      end
      resources :one_clicks, only:[:index, :show, :update] do
        collection do
          get 'state/:state', :to => 'one_clicks#index', :as => :state
          get 'return_requests'
          get 'shipment_details'
          get 'csv_export'
          patch 'update_tracking_code', :to => 'one_clicks#update_tracking_code', :as => :update_tracking_code
          patch 'update_state', :to => 'one_clicks#update_state', :as => :update_state
        end
      end
    end
    #TODO routing setting
    namespace :bills do
      resources :credits, only: [:index, :show]
      resources :post_payments, only: [:index, :show]
      resources :subscriptions
      resources :one_clicks
    end
    resources :users, only:[:index, :show, :update] do
      collection do
        post 'search'
      end
    end
    resources :reports, only:[:index]
  end

end

app/views/layouts/admins/_header.html.erb
<header class="header">
  <a class="logo">
    FiNC store
  </a>
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </a>
  </nav>
</header>

app/views/layouts/admins/_left.html.erb
<!-- Left side column. contains the logo and sidebar -->
<aside class="left-side sidebar-offcanvas">
<section class="sidebar">
<ul class="sidebar-menu">
  <li>
  <a href="<%= admins_products_path %>">
    <i class="fa fa-laptop"></i>
    <span>商品管理</span>
  </a>
  </li>
  <li class="treeview">
  <a href="<%= %>">
    <i class="fa fa-th"></i>
    <span>発送管理</span>
    <i class="fa fa-angle-left pull-right"></i>
  </a>
  <ul class="treeview-menu">
    <li><a href="<%= admins_shipments_singles_path %>"><i class="fa fa-angle-double-right"></i>単品購入</a></li>
    <li><a href="<%= admins_shipments_one_clicks_path %>"><i class="fa fa-angle-double-right"></i>弁当購入</a></li>
  </ul>
  </li>
    <% if @is_bills.nil? %>
      <li class="treeview">
      <a href="<%= %>">
        <i class="fa fa-th"></i>
        <span>請求管理</span>
        <i class="fa fa-angle-left pull-right"></i>
      </a>
      <ul class="treeview-menu">
        <li><a href="<%= admins_bills_credits_path %>"><i class="fa fa-angle-double-right"></i>クレジット管理</a></li>
        <li><a href="<%= admins_bills_one_clicks_path %>"><i class="fa fa-angle-double-right"></i>1-click決済管理</a></li>
        <li><a href="<%= admins_bills_post_payments_path %>"><i class="fa fa-angle-double-right"></i>後払い管理</a></li>
        <li><a href="<%= admins_bills_subscriptions_path %>"><i class="fa fa-angle-double-right"></i>洗替管理</a></li>
      </ul>
      </li>
    <% else %>
      <li class="treeview active">
      <a href="<%= %>">
        <i class="fa fa-th"></i>
        <span>請求管理</span>
        <i class="fa fa-angle-left pull-right"></i>
      </a>
      <ul class="treeview-menu">
        <li><a href="<%= credit_admins_bills_path %>"><i class="fa fa-angle-double-right"></i>クレジット管理</a></li>
        <li><a href="<%= post_payment_admins_bills_path %>"><i class="fa fa-angle-double-right"></i>後払い管理</a></li>
        <li><a href="<%= regular_purchase_admins_bills_path("laundering_planned")%>"><i class="fa fa-angle-double-right"></i>洗替管理</a></li>
      </ul>
      </li>
    <% end %>
    <li>
    <a href="<%= admins_reports_path %>">
      <i class="fa fa-inbox"></i>
      <span>レポート</span>
    </a>
    </li>
    <li>
    <a href="<%= admins_users_path %>">
      <i class="fa fa-inbox"></i>
      <span>ユーザー管理</span>
    </a>
    </li>
</ul>
</section>
</aside>

app/views/layouts/admins/admins.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FiNCstore</title>
  <%= stylesheet_link_tag    'admins/app', media: 'all' %>
  <%= javascript_include_tag 'admins/app' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0;">
  <%= favicon_link_tag(source='/favicon.ico', options={}) %>
</head>
<body class="skin-blue">
  <% unless current_admin.operators? %>
    <%= render :partial => "layouts/admins/header"%>
    <div class="wrapper row-offcanvas row-offcanvas-left">
      <%= render :partial => "layouts/admins/left" %>
      <aside class="right-side">
        <%= yield %>
      </aside>
    </div>
  <% else %>
    <div class="wrapper" style="padding:25px 25px">
      <%= yield %>
    </div>
  <% end %>
</body>
</html>