config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    devise_for :users, :controllers => {
      :sessions => 'users/sessions',
      :passwords => "users/passwords",
      :registrations => 'users/registrations'
    }
    devise_for :admins,
      :controllers => { :sessions => 'admins/sessions' }
  else
    devise_for :users,
      :controllers => { :sessions => 'users/sessions' },
      :only => [ :session ]
    devise_for :admins,
      :controllers => { :sessions => 'admins/sessions' },
      :only => [ :session ]
  end

  root 'users/accounts#top'

  resource :health_check, only: [:show]

  scope module: :users do
    namespace :oauth do
      resource :authorization, only: [:create] do
        get '/', action: :create
        post 'sign_in_with_email_password', action: :sign_in_with_email_password
      end
    end
    resource :account, only: [:show] do
      get '/top' => 'accounts#top', on: :collection, :as => :top
      resources :addresses, only: [:index, :edit, :update, :new, :create, :destroy] do
        collection do
          get 'fetch_address_with_zipcode', action: :fetch_address_with_zipcode, :as => :fetch_address
        end
      end
    end
    resource :profile, only: [:edit, :create, :update] do
      resources :credit_cards, only: [:index, :new, :edit, :create, :destroy]
    end
    resources :products, only: [:index, :show] do
      collection do
        get ':id/show_one_click/', action: :show_one_click, :as => :show_one_click
        get ':id/description', action: :description, :as => :description
        get 'update_max_used_point', action: :update_max_used_point, :as => :update_max_used_point
        post :post_one_click_order
      end
    end
    resource :cart, only: [:update], controller: :orders do
      get '/', action: :edit
      get :address, on: :member
      patch '/remove_item/:id' => 'orders#remove_item', on: :collection, :as => :remove_item
    end
    resources :orders, only: [:show] do
      collection do
        get 'single_history'
        get 'one_click_history'
        post :populate
        get  ':number/thanks', action: :thanks, :as => :thanks
        get  ':number/one_click_thanks', action: :one_click_thanks, :as => :one_click_thanks
        patch '/cancel/:number' => 'orders#cancel', :as => :cancel
        patch '/one_click_cancel/:number' => 'orders#one_click_cancel', :as => :one_click_cancel
      end
    end
    namespace :orders do
      resources :items, only: [] do
        get  'send_back_confirmation'
        post 'request_send_back'
      end
    end

    get '/checkout/:state', :to => 'checkouts#edit', :as => :checkout_state
    patch '/checkout/:state', :to => 'checkouts#update', :as => :update_checkout
    get '/t/*id', :to => 'taxons#show', :as => :taxons #nested_taxon
    get '/guidances/:name', :to => 'guidances#show', :as => :guidance
  end

  namespace :admins do
    resources :products do
      resources :variants, only: [:index, :new, :create, :edit, :update, :destroy]
      get '/move_position', :to => 'products#move_position', :as => :move_position
    end
    resources :variants, only: [] do
      resources :images,only: [:index, :new, :create, :edit, :update, :destroy], controller: :images, imageable_type: 'Variant'
      post '/images/sort', :to => 'images#sort'
    end
    namespace :shipments do
      resources :singles, only:[:index, :show, :update] do
        collection do
          get 'state/:state', :to => 'singles#index', :as => :state
          get 'return_requests'
          get 'shipment_details'
          get 'csv_export'
          patch 'update_tracking_code', :to => 'singles#update_tracking_code', :as => :update_tracking_code
          patch 'update_state', :to => 'singles#update_state', :as => :update_state
        end
      end
      resources :one_clicks, only:[:index, :show, :update] do
        collection do
          get 'state/:state', :to => 'one_clicks#index', :as => :state
          get 'return_requests'
          get 'shipment_details'
          get 'csv_export'
          patch 'update_tracking_code', :to => 'one_clicks#update_tracking_code', :as => :update_tracking_code
          patch 'update_state', :to => 'one_clicks#update_state', :as => :update_state
        end
      end
    end
    #TODO routing setting
    namespace :bills do
      resources :credits, only: [:index, :show]
      resources :post_payments, only: [:index, :show]
      resources :subscriptions
      resources :one_clicks
    end
    resources :users, only:[:index, :show, :update] do
      collection do
        post 'search'
      end
    end
    resources :reports, only:[:index]
  end

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < Admins::BaseController

  include Admins::AuthenticationHelper

  before_action :allow_only_admins
  before_action :set_user, only: [:show, :edit, :update]

  def index
    @users = User.includes(:profile).page(params[:page])
  end

  def show
    if params[:admin_name]
      begin
        ActiveRecord::Base.transaction do
          @me = @user.me_in_finc_app
        end
      rescue
        params[:admin_not_found] = "アプリ情報が見つかりません"
      end
    end
  end

  def edit
  end

  def update
    points = (-1) * (params[:points]).to_i
    if @user.update_used_point_total(points) && points != 0
      flash[:notice] = "マイルを#{params[:points]}増加させました"
    else
      flash[:notice] = "マイルの変更に失敗しました"
    end
    redirect_to :back
  end

  def search
    @users = User.includes(:profile).where(id: Profile.where("concat(last_name, first_name) like?", "%#{params[:name]}%").pluck(:user_id)).page(params[:page])
    flash[:notice] = @users.present? ? '' : '該当するユーザーはいません'
    render action: 'index'
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

end

app/controllers/users/accounts_controller.rb
class Users::AccountsController < Users::BaseController

  def top
    @taxons = current_user.shown_taxon
    @me = current_user
    @wellness_mileage = @me.wellness_mileage
  end

  def show
    @me = current_user
    @wellness_mileage = @me.wellness_mileage
  end

end

app/controllers/users/addresses_controller.rb
class Users::AddressesController < Users::BaseController
  include Users::AddressesHelper
  before_action :set_user
  before_action :set_continue, only: [:new]

  def index
    @addresses = @user.addresses.active
  end

  def new
    @address = Address.new
  end

  def edit
    @address = @user.addresses.find(params[:id])
  end

  def create
    @address = Address.new(address_params)
    if !Address.reach_upper_limit?(current_user)
      if @address.save
        continue_path
      else
        set_continue
        render :edit
      end
    else
      redirect_to account_addresses_path
    end
  end

  def update
    @address = @user.addresses.find(params[:id])
    if @address.update(address_params)
      redirect_to account_addresses_path
    else
      set_continue
      render :edit
    end
  end

  def destroy
    address = @user.addresses.find(params[:id])
    address.update(deleted_at: Time.now)
    redirect_to account_addresses_path
  end

  def fetch_address_with_zipcode
    pref = Zipcode.set_address_from_zipcode(params[:zipcode])
    render json: pref
  end

  private

    def set_user
      @user = User.find(current_user.id)
    end

    def address_params
      zipcode = params[:address].require(:first_zipcode) + params[:address].require(:last_zipcode)
      params.require(:address).permit(:last_name, :first_name, :address, :city, :phone).merge(user_id: @user.id, zipcode: zipcode)
    end

    def set_continue
      @continue = params[:continue] if params[:continue].present?
    end

    def continue_path
      redirect_to account_addresses_path and return if params[:continue].blank?
      if params[:continue].include?("checkout/payment")
        redirect_to checkout_state_path("payment")
      else # params[:continue].include?("profile/credit_cards/new")
        redirect_to new_profile_credit_card_path
      end
    end

end

app/controllers/users/base_controller.rb
class Users::BaseController < ApplicationController
  include Users::OrdersHelper
  before_action :authenticate_user!
  before_action :set_user
  layout "users/users"

  def set_user
    @user = current_user
    @order = current_order
  end
end

app/controllers/users/checkouts_controller.rb
class Users::CheckoutsController < Users::BaseController
  include Users::CheckoutsHelper

  before_action :redirect_to_profile_if_without_any, only: [:edit]

  before_action :load_order_with_lock
  before_action :detail
  before_action :set_state_if_present

  before_action :ensure_order_not_completed
  # before_action :ensure_checkout_allowed
  before_action :ensure_sufficient_stock_lines
  before_action :ensure_valid_state

  before_action :associate_user
  before_action :check_authorization
  before_action :apply_coupon_code

  before_action :setup_for_current_state

  def edit
  end

  def update
    if @order.update_from_params(params, permitted_checkout_attributes, request.headers.env)
      if @order.completed?
        @current_order = nil
        flash['order_completed'] = true
        UserMailer.delay.send_order_accepted_notification(@order)
        redirect_to thanks_orders_path(number: @order.single_order_detail.payment.number)
      else
        redirect_to checkout_state_path(@order.state)
      end
    elsif params['error_message'] == "item.invalid_item"
      @order.fail!
      redirect_to cart_path
    else
      render :edit
    end
  end

  private

    def redirect_to_profile_if_without_any
      if current_user.profile.blank? || current_user.profile.invalid?(:preceed_to_payment)
        redirect_to edit_profile_path(continue: checkout_state_path(state: :payment))
      end
    end

    def load_order_with_lock
      @order = current_order
      redirect_to cart_path and return unless @order
    end

    def detail
      @detail ||= @order.single_order_detail
    end

    def set_state_if_present
      if params[:state]
        redirect_to checkout_state_path(@order.state) if @order.can_go_to_state?(params[:state])
        @order.state = params[:state]
        set_common_parameter
      end
    end

    def ensure_order_not_completed
      redirect_to cart_path if @order.completed?
    end

    # def ensure_checkout_allowed
    #   unless @order.checkout_allowed?
    #     redirect_to cart_path
    #   end
    # end

    def ensure_sufficient_stock_lines
      redirect_to cart_path, notice: '商品が選ばれていません' and return if @detail.item_total.zero?
    end

    def ensure_valid_state
      if @order.state != correct_state
        flash.keep
        @order.state = correct_state
        redirect_to checkout_state_path(@order.state)
      end
    end

    def correct_state
      if unknown_state?
        @order.checkout_steps.first
      else
        @order.state
      end
    end

    def unknown_state?
      (params[:state] && !@order.has_checkout_step?(params[:state])) ||
        (!params[:state] && !@order.has_checkout_step?(@order.state))
    end

    def check_authorization
      redirect_to cart_path if current_user.nil? || @order.user_id != current_user.id
    end

    def apply_coupon_code
      # TODO implement
    end

    def setup_for_current_state
      method_name = :"before_#{@order.state}"
      send(method_name) if respond_to?(method_name, true)
    end

    def before_payment
      @gmo_cards = GmoMultiPayment::Card.new(current_user).search
      @addresses = current_user.addresses.active
      @wellness_mileage = current_user.wellness_mileage
      @max_use_point = CheckoutValidityChecker.new.items_max_used_point(current_user, @single_line_items)
      @default_address = Address.default_address(current_user)
    end

    def before_confirm
      @payment = detail.payment
      @address = Address.where(id: @payment.address_id).first
      if @payment.gmo_card_seq_temporary
        gmo_cards = GmoMultiPayment::Card.new(current_user).search
        @gmo_card = gmo_cards[@payment.gmo_card_seq_temporary]
      end
    end

    def set_common_parameter
      @items = Variant
      .where(id: @detail.single_line_items.pluck(:variant_id))
      .includes(:images, :price)
      @single_line_items = @detail.single_line_items
    end

end

app/controllers/users/credit_cards_controller.rb
class Users::CreditCardsController < Users::BaseController
  before_action :check_multi_payment_user
  before_action :set_continue, only: [:new, :create]
  before_action :year_range, only: [:new, :create]

  def index
    @gmo_cards = GmoMultiPayment::Card.new(@user).search
  end

  def new
  end

  def edit
    @card_no = params[:card_no]
    @card_seq = params[:id]
  end

  def create
    if GmoMultiPayment::Card.new(@user).search.size < GmoMultiPayment::Card::UpperLimit
      expire = params[:expire_year][2,3] + format("%02d",params[:expire_month])
      if GmoMultiPayment::Card.new(@user).create(params[:card_no], expire)
        register_credit_card_history
        redirect_to continue_path
      else
        flash[:notice] = "カード情報または、有効期限が不正です。"
        render :new
      end
    else
      redirect_to profile_credit_cards_path
    end
  end

  def destroy
    gmo_card = GmoMultiPayment::Card.new(@user)
    gmo_card.delete(params[:id])
    redirect_to profile_credit_cards_path
  end

  private

    def register_credit_card_history
      unless CreditCard.find_by(user_id: current_user.id).present?
        CreditCard.create(user_id: current_user.id, registered_at: Time.now)
      end
    end

    def check_multi_payment_user
      @user = current_user
      gmo_member = GmoMultiPayment::Member.new(@user)
      if gmo_member.search
        is_success = true
      else
        is_success = gmo_member.create
      end
      if !is_success
        session.delete(:user)
        redirect_to new_user_session_path
      end
    end

    def set_continue
      @continue = \
        if params[:continue].present?
          params[:continue]
        else
          profile_credit_cards_path
        end
    end

    def continue_path
      if params[:continue] && params[:continue].to_s.include?("checkout/payment")
        checkout_state_path("payment")
      elsif params[:continue] && params[:continue].to_s.include?("show_one_click")
        show_one_click_products_path(id: params[:continue].gsub(/[^0-9]/,""))
      else
        profile_credit_cards_path
      end
    end

    def year_range
      @year_range = *(Time.now.year..Time.now.year+20)
    end

end

app/controllers/users/guidances_controller.rb
class Users::GuidancesController < Users::BaseController

  def show
    render params[:name]
  end

end

app/controllers/users/oauth/authorizations_controller.rb
module Users
  module Oauth
    class AuthorizationsController < Users::Oauth::BaseController
      before_action :redirect_to_root_if_signed_in
      before_action :check_valid_key_and_token!, only: [:create]
      after_action :register_users_user_category

      def create
        if sign_in_with_access_token(persisted_access_token)
          redirect_to root_path
        else
          # finc_app 以外の認証も対応する必要が出たら実装する
          sign_up_with_fincapp(oauth_application, params[:access_token])
          redirect_to guidance_path(name: 'tutorial')#edit_profile_path#(continue: :credit_cards)
        end
      end

      def sign_in_with_email_password
        if @user = FincApp.sign_in(user_params[:email], user_params[:password])
          sign_in(@user)
          redirect_to after_sign_in_path_for(@user)
        else
          @user = User.new(email: user_params[:email])
          render layout: "users/users"
        end
      end

      private

        def redirect_to_root_if_signed_in
          redirect_to root_path and return if user_signed_in?
        end

        def check_valid_key_and_token!
          raise ActionController::BadRequest if params[:consumer_key].blank? ||
            params[:access_token].blank? ||
            oauth_application.blank?
        end

        def oauth_application
          @oauth_application ||= OauthApplication.where(consumer_key: params[:consumer_key]).first
        end

        def persisted_access_token
          @persisted_access_token ||= \
            OauthAccessToken.where(oauth_application_id: oauth_application.id) \
            .where(token: params[:access_token]).first
        end

        def sign_up_with_fincapp(oauth_finc_app, access_token)
          fincapp_user = FincApp.me(access_token)
          @user = FincApp.save_user_from_finc_app(fincapp_user)
          @user.oauth_access_tokens.where(oauth_application_id: oauth_finc_app.id) \
            .where(token: access_token).first_or_create
          sign_in(:user, @user)
          @user
        end

        def sign_in_with_access_token(persisted_access_token)
          if persisted_access_token && @user = User.where(id: persisted_access_token.user_id).first
            sign_in(:user, @user)
            @user
          end
        end

        def user_params
          params.require(:user).permit(:email, :password, :remember_me)
        end

        def register_users_user_category
          @user.first_or_initialize_users_user_category if @user.present?
        end

    end
  end
end

app/controllers/users/oauth/base_controller.rb
module Users
  module Oauth
    class BaseController < ActionController::Base
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  layout "users/users"
end

app/controllers/users/taxons_controller.rb
class Users::TaxonsController < Users::BaseController

  include Users::ProductsHelper

  def show
    @taxon = Taxon.find(params[:id])

    @taxon.leaf? ? top_products : @products = Product.none
  end

  private

end

app/views/users/checkouts/_confirm.html.erb
<%= form_tag(checkout_state_path(state: :confirm), :method => :patch) do %>

  <div class="p-wrapper--have_padding">
    <h2 class="title">注文確定</h2>
    <div class="u-margin__bottom_middle">
      <%= submit_tag "注文の確定", class: 'c-btn--submit c-btn--submit--single', :onclick=> "prevent_double_submit(event)" %>
    </div>
    <h2 class="c-links__title">注文内容</h2>
    <ul class="p-payment_method_selections">
      <li class="p-payment_method_selection">
        <span>
<%if false %>
        商品: <%= number_to_jpy(@detail.item_total_with_tax) %><br>
<% end %>
        商品: <%= number_to_jpy(@detail.item_total) %><br>
        送料: <%= number_to_jpy(@detail.shipment_total) %>
        </span>
      </li>
      <li class="p-payment_method_selection">
        <span>
          使用マイル: <%= @payment.used_point %> mile<br>
          ご請求金額: <%= number_to_jpy(@payment.amount) %>
        </span>
      </li>
    </ul>

    <h2 class="c-links__title">お届け先住所</h2>
    <ul class="p-payment_method_selections">
      <li class="p-payment_method_selection">
        <span>
          <%= @address.last_name %>&nbsp;<%= @address.first_name %><br>
          <%= @address.zipcode %>&nbsp;<%= @address.city %>&nbsp;<%= @address.address %><br>
        </span>
      </li>
    </ul>

    <h2 class="c-links__title">支払い方法</h2>
    <ul class="p-payment_method_selections">
      <li class="p-payment_method_selection">
        <span>
          <%= @gmo_card[:CardNo] %>
        </span>
      </li>
    </ul>

    <h2 class="c-links__title">購入詳細</h2>
    <% if false #TODO %>
      <div class="c-payment_method_section">
        購入形式: <%= t('order_type.single_order') %>
      </div>
    <% end %>
    <% @items.each do |item| %>
      <div class="c-product_list">
        <div class="c-product_list__image">
          <%= image_tag item.top_image %>
        </div>
        <div class="c-product__list_detail_wrapper">
          <div class="c-product_list__title">
            <%= item.name %>
          </div>
          <div class="c-product_list__price">
            <%= number_to_jpy(item.price.amount) %>(<%= @single_line_items.where(variant_id: item.id).first.quantity %>個)
          </div>
        </div>
      </div>
    <% end %>
    <div class="c-btn--submit">
      <%= submit_tag "注文の確定", class: 'c-btn--submit c-btn--submit--single', :onclick=> "prevent_double_submit(event)" %>
    </div>
  </div>

<% end %>

app/views/users/checkouts/_payment.html.erb
<%= form_tag(checkout_state_path(state: :payment), :method => :patch) do %>
  <div class="p-wrapper--have_padding">
    <h2 class="title">
      カート小計(<%=@detail.item_count%>個の商品):
      <span><%=number_to_jpy(@detail.item_total)%></span><br>
      <div class="c-payment_jquery_notice u-margin__top5">
        <%if params['error_message'].present? %>
          <div class="u-margin__top10 u-margin__bottom10">
            <% if params['error_message'] == 'payment_attributes_error.used_point_over_limit' %>
              <%= t(params['error_message'], :limit => Payment::UsedPointLimit+1) %>
            <% else %>
              <%= t(params['error_message'], :default => "入力項目に不備があります") %>
            <% end %>
          </div>
        <% end %>
      </div>
    </h2>
    <div class="c-btn--submit u-margin__bottom_middle">
      <%= submit_tag "購入確認画面へ", class: 'c-btn--submit c-btn--submit--single', :onclick=> "prevent_double_submit(event)" %>
    </div>
    <h2 class="c-links__title">お届先住所</h2>
    <ul class="c-links">
      <% @addresses.each do |address| %>
        <li class="c-link--small_text--nolink">
          <div class="c-link__radio_div">
            <%= radio_button_tag "order[address_id]", address.id, check_as_default_address(address, @default_address) %>
          </div>
          <%= label_tag "order_address_id_#{address.id}",
            "#{address.name}<br>
            #{address.full_address}".html_safe %>
            </li>
          <% end %>
          <% if @addresses.size < Address::UpperLimit %>
            <div class="address-highlighted">
              <%= link_to(new_account_address_path(continue: checkout_state_path(state: :payment))) do %>
                <li class="c-link">新規住所登録</li>
              <% end %>
            </div>
          <% else %>
            <li class="c-link"><%= t('validate_registration.address') %></li>
          <% end %>
        </ul>
        <h2 class="c-links__title">支払い方法</h2>
        <ul class="c-links u-margin__bottom_middle">
          <li class="c-link--nolink">
          <div class="c-link__radio_div">
            <%= radio_button_tag "order[payment_attributes[payment_method_id]]", 1, nil, :onclick=> "payment_method_change(this.value)", checked: "checked" %>
          </div>
          <p>
          <%= label_tag "payment_method_id_1", "クレジット" %>
          </li>
          <% if false #FIXME%>
            <li class="c-link--nolink">
            <div class="c-link__radio_div">
              <%= radio_button_tag "order[payment_attributes[payment_method_id]]", 2, nil, :onclick=> "payment_method_change(this.value)" %>
            </div>
            <%= label_tag "payment_method_id_2", "後払い決済" %>
            </li>
          <% end %>
        </ul>
        <ul class="c-links js-credit">
          <% @gmo_cards.each_with_index do |gmo_card, i| %>
            <li class="c-link--small_text--nolink">
            <div class="c-link__radio_div">
              <%= radio_button_tag "order[payment_attributes[gmo_card_seq_temporary]]", gmo_card[:CardSeq], i == 0 ? 'checked: "checked"' : nil %>
            </div>
            <%= label_tag "order_payment_attributes_gmo_card_seq_temporary_#{gmo_card[:CardSeq]}", "番号：#{gmo_card[:CardNo]}<br />有効期限：#{gmo_card[:Expire]}".html_safe %>
            </li>
          <% end %>
          <% if @gmo_cards.size < GmoMultiPayment::Card::UpperLimit %>
            <div class="credit-highlighted">
              <%= link_to(new_profile_credit_card_path(continue: checkout_state_path(state: :payment))) do %>
                <li class="c-link">新規クレジット登録</li>
              <% end %>
            </div>
          <% else %>
            <li class="c-link"><%= t('validate_registration.address') %></li>
          <% end %>
        </ul>
        <ul class="c-links js-cresit">
          <% @gmo_cards.each do |gmo_card| %>
            <li class="c-link--small_text--nolink">
            <div class="c-link__radio_div">
              <%= radio_button_tag "order[payment_attributes[gmo_card_seq_temporary]]", gmo_card[:CardSeq] %>
            </div>
            <span>
              番号：<%= gmo_card[:CardNo] %> <br />
              有効期限： <%= gmo_card[:Expire] %>
            </span>
            </li>
          <% end %>
        </ul>
        <h2 class="c-links__title">使用するマイル</h2>
        <ul class="p-payment_method_selections">
          <li class="p-payment_method_selection">
          <div class="p-payment_method_selection__radio">
            <%= radio_button_tag "order[use_all_point]", true %>
          </div>
          <%= label_tag "order_use_all_point_true", "全て使用", class: "p-payment_method_selection__title" %>
          <p class="p-payment_method_selection__price"><%= @max_use_point %> マイル</p>
          </li>
          <li class="p-payment_method_selection">
          <div class="p-payment_method_selection__radio">
            <%= radio_button_tag "order[use_all_point]", false, checked: true %>
          </div>
          <%= label_tag "order_use_all_point_false", "一部を使用", class: "p-payment_method_selection__title" %>
          <div class="p-payment_method__detail is-active">
            <%= text_field_tag "order[used_point]", 0, min: 0, max: @max_use_point, class: 'p-payment_method__amount' %>
            <p class="u-margin__left_short">マイル</p>
          </div>
          </li>
        </ul>
        <h2 class="c-links__title">購入詳細</h2>
        <% if false #FIXME %>
          <div class="c-payment_method_section">
            購入形式: <%= t('order_type.single_order') %>
          </div>
        <% end %>
        <% @items.each do |item| %>
          <div class="c-product_list">
            <div class="c-product_list__image">
              <%= image_tag item.top_image %>
            </div>
            <div class="c-product__list_detail_wrapper">
              <div class="c-product_list__title">
                <%= item.name %>
              </div>
              <div class="c-product_list__price">
                <%= number_to_jpy(item.price.amount) %>(<%= @single_line_items.where(variant_id: item.id).pluck(:quantity).first %>個)
              </div>
            </div>
          </div>
        <% end %>
    <div class="c-btn--submit">
      <%= submit_tag "購入確認画面へ", class: 'c-btn--submit c-btn--submit--single', :onclick=> "prevent_double_submit(event)" %>
    </div>
  </div>
<%# TODO subscription %>

<% end %>

app/views/users/checkouts/_thanks.html.erb
<div class="p-wrapper--have_padding">
  <h2 class="title">ご購入ありがとうございました。</h2>
  <h2 class="title">注文番号: 10302043-23423</h2>
</div>

app/views/users/checkouts/edit.html.erb
<% case params[:state] %>
<% when "payment" %>
  <%= render partial: 'users/checkouts/payment', locals: {} %>
<% when "confirm" %>
  <%= render partial: 'users/checkouts/confirm', locals: {} %>
<% end %>